// apps/web-angular/src/app/onboarding/components/tabs/overview-tab/overview-tab.component.ts
import { Component, inject, Output, EventEmitter } from '@angular/core';
import { OnboardingMockService } from '../../../services/onboarding-mock.service';
import { CaseStatus, AuditEvent, COUNTRIES, TEAMS, CONTRACT_TYPES } from '../../../models/onboarding-case.model';

const JOURNEY_STAGES: { id: CaseStatus; label: string }[] = [
  { id: 'draft',                     label: 'Borrador' },
  { id: 'candidate_invited',         label: 'Formulario enviado' },
  { id: 'candidate_submitted',       label: 'Datos recibidos' },
  { id: 'hr_review',                 label: 'Revisión RRHH' },
  { id: 'ready_to_activate',         label: 'Listo para activar' },
  { id: 'active_pending_automation', label: 'Automatización' },
  { id: 'operative',                 label: 'Operativo' },
];

const ACTION_LABELS: Record<string, string> = {
  case_created: 'Caso creado', candidate_form_sent: 'Formulario enviado al candidato',
  candidate_form_submitted: 'Datos enviados por candidato', review_started: 'Revisión RRHH iniciada',
  correction_requested: 'Corrección solicitada', case_approved: 'Caso aprobado',
  case_activated: 'Activación iniciada', case_blocked: 'Caso bloqueado',
  case_unblocked: 'Caso desbloqueado', case_cancelled: 'Caso cancelado',
  case_operative: 'Caso operativo', task_completed: 'Tarea completada',
  task_failed: 'Tarea fallida', task_skipped: 'Tarea omitida',
  email_approved: 'Plantilla de email aprobada', candidate_data_consolidated: 'Datos consolidados',
};

@Component({
  selector: 'app-overview-tab',
  standalone: true,
  template: `
    @if (svc.selectedCase(); as c) {
      <div class="space-y-6">
        <!-- Identity header -->
        <div class="flex items-start gap-3 lg:gap-4 pb-2">
          <div class="w-11 h-11 rounded-full flex items-center justify-center text-sm font-bold text-white flex-shrink-0" style="background: var(--brand-primary)">
            {{ c.employee.name.charAt(0) }}{{ c.employee.lastName.charAt(0) }}
          </div>
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-3 flex-wrap">
              <h2 class="text-lg lg:text-[22px] font-bold leading-tight text-[var(--text-primary)] truncate">
                {{ c.employee.name }} {{ c.employee.lastName }}
              </h2>
              <span class="text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded border"
                [style.backgroundColor]="statusBg(c.status)"
                [style.color]="statusColor(c.status)"
                [style.borderColor]="statusColor(c.status) + '33'">
                {{ statusLabel(c.status) }}
              </span>
            </div>
            <div class="flex items-center gap-2.5 mt-1 text-xs text-[var(--text-secondary)] flex-wrap">
              <span>{{ c.employee.role }}</span>
              <span class="text-[var(--text-tertiary)]">·</span>
              <span class="uppercase font-mono">{{ teamLabel(c.employee.team) }}</span>
            </div>
            <div class="flex items-center gap-3 mt-2 text-[11px] text-[var(--text-tertiary)] flex-wrap">
              <span>{{ c.employee.cityId }}, {{ countryName(c.employee.countryId) }}</span>
              <span class="text-[var(--text-tertiary)]">·</span>
              <span>Inicio: {{ formatDate(c.employee.startDate) }}</span>
              <span class="text-[var(--text-tertiary)]">·</span>
              <span class="text-[var(--brand-primary)] font-bold uppercase tracking-wider">
                {{ nextStep(c.status, c.candidateData?.consolidated ?? false) }}
              </span>
            </div>
          </div>
        </div>

        <!-- Status banner -->
        @if (c.status === 'blocked' || c.status === 'cancelled' || c.correctionNote) {
          <div class="rounded-xl border p-4 flex items-start gap-3"
            [class]="c.status === 'blocked' ? 'bg-[var(--status-error-subtle)]' : c.status === 'cancelled' ? 'bg-[var(--bg-elevated)]' : 'bg-[var(--status-warning-subtle)]'"
            [style.borderColor]="c.status === 'blocked' ? 'rgba(220,38,38,0.2)' : c.status === 'cancelled' ? 'var(--border-default)' : 'rgba(217,119,6,0.2)'"
          >
            <div class="min-w-0">
              <p class="text-sm font-bold" [style.color]="c.status === 'blocked' ? 'var(--status-error)' : c.status === 'cancelled' ? 'var(--text-primary)' : 'var(--status-warning)'">
                {{ c.status === 'blocked' ? 'Caso bloqueado' : c.status === 'cancelled' ? 'Caso cancelado' : 'Corrección solicitada al candidato' }}
              </p>
              @if (c.blockReason && c.status === 'blocked') { <p class="text-xs text-[var(--text-secondary)] mt-1">{{ c.blockReason }}</p> }
              @if (c.correctionNote && c.status !== 'blocked' && c.status !== 'cancelled') { <p class="text-xs text-[var(--text-secondary)] mt-1">{{ c.correctionNote }}</p> }
            </div>
          </div>
        }

        <div class="flex flex-col lg:flex-row gap-6">
          <!-- Journey -->
          <section class="flex-1 min-w-0 bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6">
            <div class="flex items-baseline justify-between mb-6 gap-3 flex-wrap">
              <h3 class="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider">Trayecto del caso</h3>
              <span class="text-[11px] font-medium text-[var(--text-tertiary)]">Paso {{ currentIndex(c.status, c.auditLog) + 1 }} de {{ journeyStages.length }}</span>
            </div>
            <ol class="relative">
              @for (stage of journeyStages; track stage.id; let i = $index; let last = $last) {
                <li class="relative flex items-start pb-6 last:pb-0">
                  @if (!last) {
                    <span class="absolute left-3 top-6 bottom-0 w-px -ml-px"
                      [class]="i < currentIndex(c.status, c.auditLog) || (c.status === 'operative' && i <= currentIndex(c.status, c.auditLog)) ? 'bg-[var(--brand-primary)]' : 'bg-[var(--border-subtle)]'"
                    ></span>
                  }
                  <div class="relative flex items-center justify-center w-6 h-6 rounded-full bg-[var(--bg-elevated)] z-10 flex-shrink-0 mr-3">
                    @if (i < currentIndex(c.status, c.auditLog) || (c.status === 'operative' && last)) {
                      <svg class="w-5 h-5 text-[var(--brand-primary)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                    } @else if (i === currentIndex(c.status, c.auditLog) && c.status !== 'operative') {
                      <span class="w-3 h-3 rounded-full bg-[var(--brand-primary)] ring-4 ring-[var(--brand-primary-subtle)]"></span>
                    } @else {
                      <span class="w-2.5 h-2.5 rounded-full border-2 border-[var(--border-default)]"></span>
                    }
                  </div>
                  <div class="flex-1 min-w-0 pt-0.5">
                    <p class="text-sm"
                      [class]="i === currentIndex(c.status, c.auditLog) && c.status !== 'operative' ? 'text-[var(--brand-primary)] font-bold'
                        : (i < currentIndex(c.status, c.auditLog) || (c.status === 'operative' && last)) ? 'text-[var(--text-primary)] font-medium'
                        : 'text-[var(--text-secondary)] font-medium'"
                    >{{ stage.label }}</p>
                    @if (i === currentIndex(c.status, c.auditLog) && c.status !== 'operative') {
                      <p class="text-[11px] uppercase tracking-wider font-semibold text-[var(--brand-primary)] mt-1">Etapa actual</p>
                    }
                  </div>
                </li>
              }
            </ol>
          </section>

          <!-- Right: next + recent -->
          <aside class="w-full lg:w-80 flex-shrink-0 space-y-6 min-w-0">
            <div class="bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6">
              <h3 class="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider mb-3">Siguiente hito</h3>
              <p class="text-sm font-semibold text-[var(--text-primary)] leading-snug">{{ milestone(c.status, hasFailedTasks(c.tasks)) }}</p>
              @if (c.status === 'operative') {
                <p class="text-xs text-[var(--status-success)] mt-2 font-medium">El alta operativa fue completada.</p>
              }
            </div>

            <div class="bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6">
              <div class="flex items-baseline justify-between mb-4 gap-3 flex-wrap">
                <h3 class="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider">Actividad reciente</h3>
                <button (click)="navigateTo.emit('audit')" class="text-[10px] font-semibold text-[var(--brand-primary)] uppercase tracking-wider hover:underline">
                  Ver auditoría completa →
                </button>
              </div>
              @if (recentEvents(c.auditLog).length === 0) {
                <p class="text-sm text-[var(--text-tertiary)]">Sin actividad registrada</p>
              } @else {
                <ul class="relative pl-5">
                  @for (ev of recentEvents(c.auditLog); track ev.id; let i = $index) {
                    <li class="relative pb-4 last:pb-0">
                      @if (i < recentEvents(c.auditLog).length - 1) {
                        <span class="absolute bg-[var(--border-subtle)]" style="left: -13px; top: 13px; bottom: -4px; width: 1px"></span>
                      }
                      <span class="absolute z-10 rounded-full border-2 border-[var(--border-default)] bg-[var(--bg-base)]" style="left: -17px; top: 4px; width: 8px; height: 8px"></span>
                      <p class="text-sm font-medium text-[var(--text-primary)]">{{ actionLabel(ev.action) }}</p>
                      <div class="flex items-center gap-2 mt-1 flex-wrap">
                        <span class="text-[10px] font-semibold px-1.5 py-0.5 rounded uppercase tracking-wide"
                          [class]="ev.actorType === 'system' ? 'bg-[var(--status-success-subtle)] text-[var(--status-success)]'
                            : ev.actorId === 'candidate' ? 'bg-[var(--status-info-subtle)] text-[var(--status-info)]'
                            : 'bg-[var(--brand-primary-subtle)] text-[var(--brand-primary)]'"
                        >{{ ev.actorType === 'system' || ev.actorType === 'integration' ? 'Sistema' : ev.actorId === 'candidate' ? 'Candidato' : 'RRHH' }}</span>
                        <span class="text-xs text-[var(--text-tertiary)]">{{ relativeTime(ev.timestamp) }}</span>
                      </div>
                    </li>
                  }
                </ul>
              }
            </div>
          </aside>
        </div>
      </div>
    }
  `,
})
export class OverviewTabComponent {
  readonly svc = inject(OnboardingMockService);
  @Output() navigateTo = new EventEmitter<string>();

  readonly journeyStages = JOURNEY_STAGES;

  statusLabel(s: CaseStatus): string {
    const m: Record<string, string> = { draft: 'Borrador', candidate_invited: 'Invitado', candidate_submitted: 'Enviado', hr_review: 'En revisión', ready_to_activate: 'Listo', active_pending_automation: 'Procesando', operative: 'Operativo', blocked: 'Bloqueado', cancelled: 'Cancelado' };
    return m[s] || s;
  }
  statusColor(s: CaseStatus): string {
    const m: Record<string, string> = { draft: 'var(--text-secondary)', blocked: 'var(--status-error)', operative: 'var(--status-success)', cancelled: 'var(--text-tertiary)', hr_review: 'var(--status-warning)', active_pending_automation: 'var(--status-warning)' };
    return m[s] || 'var(--status-info)';
  }
  statusBg(s: CaseStatus): string {
    const m: Record<string, string> = { operative: 'var(--status-success-subtle)', blocked: 'var(--status-error-subtle)', hr_review: 'var(--status-warning-subtle)', active_pending_automation: 'var(--status-warning-subtle)' };
    return m[s] || 'var(--status-info-subtle)';
  }
  teamLabel(t: string): string { return TEAMS.find(x => x.value === t)?.label || t; }
  countryName(c: string): string { return COUNTRIES.find(x => x.code === c)?.name || c; }
  formatDate(d: string): string { return new Date(d + 'T00:00:00').toLocaleDateString('es-AR', { dateStyle: 'medium' }); }

  nextStep(status: CaseStatus, consolidated: boolean): string {
    const m: Record<string, string> = {
      draft: 'Paso: Enviar formulario', candidate_invited: 'Paso: Esperando candidato',
      candidate_submitted: 'Paso: Iniciar revisión', ready_to_activate: 'Paso: Activar Workspace',
      active_pending_automation: 'Paso: Tareas en curso', operative: 'Paso: Colaborador Operativo',
      blocked: 'Paso: Resolver bloqueo', cancelled: 'Paso: Caso archivado',
    };
    if (status === 'hr_review') return consolidated ? 'Paso: Aprobar onboarding' : 'Paso: Consolidar datos';
    return m[status] || '';
  }

  hasFailedTasks(tasks: any[]): boolean { return tasks.some(t => t.status === 'failed'); }

  milestone(status: CaseStatus, hasFailed: boolean): string {
    const m: Record<string, string> = {
      draft: 'Enviar formulario al candidato', candidate_invited: 'Esperar respuesta del candidato',
      candidate_submitted: 'Revisar datos enviados', hr_review: 'Consolidar datos y aprobar caso',
      ready_to_activate: 'Activar onboarding', operative: 'Caso operativo',
      blocked: 'Resolver bloqueo para retomar el alta', cancelled: 'Caso cancelado',
    };
    if (status === 'active_pending_automation') return hasFailed ? 'Resolver tareas con atención' : 'Automatización en curso';
    return m[status] || 'Sin acciones pendientes';
  }

  currentIndex(status: CaseStatus, auditLog: AuditEvent[]): number {
    const idx = JOURNEY_STAGES.findIndex(s => s.id === status);
    if (idx !== -1) return idx;
    return 0;
  }

  recentEvents(log: AuditEvent[]): AuditEvent[] {
    return [...log].sort((a, b) => b.timestamp - a.timestamp).slice(0, 5);
  }

  actionLabel(action: string): string { return ACTION_LABELS[action] || 'Acción registrada'; }

  relativeTime(ts: number): string {
    const diff = Date.now() - ts;
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return 'ahora';
    if (mins < 60) return `hace ${mins}m`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `hace ${hrs}h`;
    return `hace ${Math.floor(hrs / 24)}d`;
  }
}

// src/components/rrhh/tabs/OverviewTab.tsx
import { useStore } from '../../../store';
import { ShieldAlert, XCircle, ArrowRight, CheckCircle2, MapPin, Calendar } from 'lucide-react';
import { cn } from '../../../utils/cn';
import type { AuditEvent, CaseStatus } from '../../../types';
import { COUNTRIES, TEAMS, CONTRACT_TYPES } from '../../../types';
import { Avatar } from '../../ui/Avatar';
import { Badge } from '../../ui/Badge';

// ─── Action labels (Spanish) ────────────────────────────────────────────────
// Source of truth lives in store.ts; we only translate for display.
const ACTION_LABELS: Record<string, string> = {
  case_created: 'Caso creado',
  candidate_form_sent: 'Formulario enviado al candidato',
  candidate_form_submitted: 'Datos enviados por candidato',
  review_started: 'Revisión RRHH iniciada',
  correction_requested: 'Corrección solicitada',
  case_approved: 'Caso aprobado',
  case_activated: 'Activación iniciada',
  case_blocked: 'Caso bloqueado',
  case_unblocked: 'Caso desbloqueado',
  case_cancelled: 'Caso cancelado',
  case_operative: 'Caso operativo',
  task_completed: 'Tarea completada',
  task_failed: 'Tarea fallida',
  task_skipped: 'Tarea omitida',
  email_approved: 'Plantilla de email aprobada',
  candidate_data_consolidated: 'Datos consolidados',
};

function actionLabel(action: string): string {
  return ACTION_LABELS[action] || 'Acción registrada';
}

function formatRelativeTime(timestamp: number): string {
  const diff = Date.now() - timestamp;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'ahora';
  if (mins < 60) return `hace ${mins}m`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `hace ${hrs}h`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `hace ${days}d`;
  return new Date(timestamp).toLocaleDateString('es-AR', { day: '2-digit', month: '2-digit', year: 'numeric' });
}

// ─── Journey stages ─────────────────────────────────────────────────────────
// Canonical Phase 7F stage labels. Internal status ids stay in English.
const JOURNEY_STAGES: { id: CaseStatus; label: string }[] = [
  { id: 'draft', label: 'Borrador' },
  { id: 'candidate_invited', label: 'Formulario enviado' },
  { id: 'candidate_submitted', label: 'Datos recibidos' },
  { id: 'hr_review', label: 'Revisión RRHH' },
  { id: 'ready_to_activate', label: 'Listo para activar' },
  { id: 'active_pending_automation', label: 'Automatización' },
  { id: 'operative', label: 'Operativo' },
];

function nextMilestone(status: CaseStatus, hasFailedTasks: boolean): string {
  switch (status) {
    case 'draft': return 'Enviar formulario al candidato';
    case 'candidate_invited': return 'Esperar respuesta del candidato';
    case 'candidate_submitted': return 'Revisar datos enviados';
    case 'hr_review': return 'Consolidar datos y aprobar caso';
    case 'ready_to_activate': return 'Activar onboarding';
    case 'active_pending_automation':
      return hasFailedTasks ? 'Resolver tareas con atención' : 'Automatización en curso';
    case 'operative': return 'Caso operativo';
    case 'blocked': return 'Resolver bloqueo para retomar el alta';
    case 'cancelled': return 'Caso cancelado';
    default: return 'Sin acciones pendientes';
  }
}

// Resolve which stage the case currently maps to, including blocked/cancelled
// cases (which fall outside the linear journey).
function resolveCurrentIndex(status: CaseStatus, auditLog: AuditEvent[]): number {
  const directIndex = JOURNEY_STAGES.findIndex(s => s.id === status);
  if (directIndex !== -1) return directIndex;

  if (status === 'blocked' || status === 'cancelled') {
    const reached = auditLog.reduce((max, e) => {
      const idByAction: Record<string, CaseStatus | undefined> = {
        case_created: 'draft',
        candidate_form_sent: 'candidate_invited',
        candidate_form_submitted: 'candidate_submitted',
        review_started: 'hr_review',
        case_approved: 'ready_to_activate',
        case_activated: 'active_pending_automation',
        case_operative: 'operative',
      };
      const stageId = idByAction[e.action];
      if (!stageId) return max;
      const idx = JOURNEY_STAGES.findIndex(s => s.id === stageId);
      return idx > max ? idx : max;
    }, 0);
    return reached;
  }

  return 0;
}

function actorBadgeLabel(event: AuditEvent): string {
  if (event.actorType === 'system' || event.actorType === 'integration') return 'Sistema';
  if (event.actorId === 'candidate') return 'Candidato';
  return 'RRHH';
}

function actorBadgeClass(event: AuditEvent): string {
  if (event.actorType === 'system' || event.actorType === 'integration') {
    return 'bg-[var(--status-success-subtle)] text-[var(--status-success)]';
  }
  if (event.actorId === 'candidate') {
    return 'bg-[var(--status-info-subtle)] text-[var(--status-info)]';
  }
  return 'bg-[var(--brand-primary-subtle)] text-[var(--brand-primary)]';
}

interface OverviewTabProps {
  onOpenAudit?: () => void;
}

export function OverviewTab({ onOpenAudit }: OverviewTabProps = {}) {
  const selectedCase = useStore(state => state.getSelectedCase());
  if (!selectedCase) return null;

  const { employee, candidateData, auditLog, status, blockReason, tasks, correctionNote } = selectedCase;
  const country = COUNTRIES.find(c => c.code === employee.countryId);
  const team = TEAMS.find(t => t.value === employee.team);
  const contractType = CONTRACT_TYPES.find(c => c.value === employee.contractType);
  const isConsolidated = candidateData?.consolidated === true;
  const hasFailedTasks = tasks.some(t => t.status === 'failed');
  const currentIndex = resolveCurrentIndex(status, auditLog);
  const sortedEvents = [...auditLog].sort((a, b) => b.timestamp - a.timestamp).slice(0, 5);

  const isBlocked = status === 'blocked';
  const isCancelled = status === 'cancelled';
  const isOperative = status === 'operative';

  return (
    <div className="space-y-6">
      {/* Identity header — only visible on this tab */}
      <div className="flex items-start gap-3 lg:gap-4 pb-2">
        <Avatar name={employee.name} lastName={employee.lastName} size="lg" />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3 flex-wrap">
            <h2 className="text-lg lg:text-[22px] font-bold leading-tight text-[var(--text-primary)] truncate">
              {employee.name} {employee.lastName}
            </h2>
            <Badge
              status={status}
              pulse={status === 'candidate_submitted' || status === 'active_pending_automation'}
            />
          </div>
          <div className="flex items-center gap-2.5 mt-1 text-xs text-[var(--text-secondary)] flex-wrap">
            <span>{employee.role}</span>
            <span className="text-[var(--text-tertiary)] font-light">·</span>
            <span className="uppercase font-mono">{team?.label || employee.team}</span>
            <span className="text-[var(--text-tertiary)] font-light">·</span>
            <span>{contractType?.label || employee.contractType}</span>
          </div>
          <div className="flex items-center gap-3 mt-2 text-[11px] text-[var(--text-tertiary)] flex-wrap">
            <span className="flex items-center gap-1">
              <MapPin className="w-3.5 h-3.5" aria-hidden="true" />
              <span>{employee.cityId}, {country?.name || employee.countryId}</span>
            </span>
            <span className="text-[var(--text-tertiary)] font-light">·</span>
            <span className="flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5" aria-hidden="true" />
              <span>Inicio: {new Date(employee.startDate + 'T00:00:00').toLocaleDateString('es-AR', { dateStyle: 'medium' })}</span>
            </span>
            <span className="text-[var(--text-tertiary)] font-light">·</span>
            <span className="text-[var(--brand-primary)] font-bold uppercase tracking-wider">
              {status === 'draft' && 'Paso: Enviar formulario'}
              {status === 'candidate_invited' && 'Paso: Esperando candidato'}
              {status === 'candidate_submitted' && 'Paso: Iniciar revisión'}
              {status === 'hr_review' && (!isConsolidated ? 'Paso: Consolidar datos' : 'Paso: Aprobar onboarding')}
              {status === 'ready_to_activate' && 'Paso: Activar Workspace'}
              {status === 'active_pending_automation' && 'Paso: Tareas en curso'}
              {status === 'operative' && 'Paso: Colaborador Operativo'}
              {status === 'blocked' && 'Paso: Resolver bloqueo'}
              {status === 'cancelled' && 'Paso: Caso archivado'}
            </span>
          </div>
        </div>
      </div>

      {/* Top status banner — only when the case is outside the calm happy path */}
      {(isBlocked || isCancelled || correctionNote) && (
        <div className={cn(
          'rounded-xl border p-4 flex items-start gap-3',
          isBlocked
            ? 'bg-[var(--status-error-subtle)] border-[var(--status-error)]/20'
            : isCancelled
              ? 'bg-[var(--bg-elevated)] border-[var(--border-default)]'
              : 'bg-[var(--status-warning-subtle)] border-[var(--status-warning)]/20'
        )}>
          {isBlocked ? (
            <ShieldAlert className="w-5 h-5 text-[var(--status-error)] flex-shrink-0 mt-0.5" aria-hidden="true" />
          ) : isCancelled ? (
            <XCircle className="w-5 h-5 text-[var(--text-tertiary)] flex-shrink-0 mt-0.5" aria-hidden="true" />
          ) : (
            <ShieldAlert className="w-5 h-5 text-[var(--status-warning)] flex-shrink-0 mt-0.5" aria-hidden="true" />
          )}
          <div className="min-w-0">
            <p className={cn(
              'text-sm font-bold',
              isBlocked ? 'text-[var(--status-error)]' : isCancelled ? 'text-[var(--text-primary)]' : 'text-[var(--status-warning)]'
            )}>
              {isBlocked ? 'Caso bloqueado' : isCancelled ? 'Caso cancelado' : 'Corrección solicitada al candidato'}
            </p>
            {isBlocked && blockReason && (
              <p className="text-xs text-[var(--text-secondary)] mt-1 break-words">{blockReason}</p>
            )}
            {correctionNote && !isBlocked && !isCancelled && (
              <p className="text-xs text-[var(--text-secondary)] mt-1 break-words">{correctionNote}</p>
            )}
          </div>
        </div>
      )}

      <div className="flex flex-col lg:flex-row gap-6">
        {/* Journey */}
        <section
          aria-label="Trayecto del caso"
          className="flex-1 min-w-0 bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6"
        >
          <div className="flex items-baseline justify-between mb-6 gap-3 flex-wrap">
            <h3 className="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider">
              Trayecto del caso
            </h3>
            <span className="text-[11px] font-medium text-[var(--text-tertiary)]">
              Paso {Math.min(currentIndex + 1, JOURNEY_STAGES.length)} de {JOURNEY_STAGES.length}
            </span>
          </div>

          <ol className="relative">
            {JOURNEY_STAGES.map((stage, index) => {
              const isPast = index < currentIndex || isOperative && index <= currentIndex;
              const isCurrent = index === currentIndex && !isOperative;
              const isLast = index === JOURNEY_STAGES.length - 1;

              let state: 'completed' | 'current' | 'pending' | 'blocked' | 'cancelled' = 'pending';
              if (isPast) state = 'completed';
              if (isCurrent) state = 'current';
              if (isCurrent && isBlocked) state = 'blocked';
              if (isCurrent && isCancelled) state = 'cancelled';
              if (isOperative && isLast) state = 'completed';

              return (
                <li key={stage.id} className="relative flex items-start pb-6 last:pb-0">
                  {!isLast && (
                    <span
                      aria-hidden="true"
                      className={cn(
                        'absolute left-3 top-6 bottom-0 w-px -ml-px',
                        state === 'completed' ? 'bg-[var(--brand-primary)]' : 'bg-[var(--border-subtle)]'
                      )}
                    />
                  )}
                  <div className="relative flex items-center justify-center w-6 h-6 rounded-full bg-[var(--bg-elevated)] z-10 flex-shrink-0 mr-3">
                    {state === 'completed' && (
                      <CheckCircle2 className="w-5 h-5 text-[var(--brand-primary)]" aria-label="Etapa completada" />
                    )}
                    {state === 'current' && (
                      <span className="w-3 h-3 rounded-full bg-[var(--brand-primary)] ring-4 ring-[var(--brand-primary-subtle)]" aria-label="Etapa actual" />
                    )}
                    {state === 'pending' && (
                      <span className="w-2.5 h-2.5 rounded-full border-2 border-[var(--border-default)]" aria-label="Etapa pendiente" />
                    )}
                    {state === 'blocked' && (
                      <ShieldAlert className="w-5 h-5 text-[var(--status-error)]" aria-label="Etapa bloqueada" />
                    )}
                    {state === 'cancelled' && (
                      <XCircle className="w-5 h-5 text-[var(--text-tertiary)]" aria-label="Etapa cancelada" />
                    )}
                  </div>
                  <div className="flex-1 min-w-0 pt-0.5">
                    <p className={cn(
                      'text-sm',
                      state === 'current' ? 'text-[var(--brand-primary)] font-bold' :
                      state === 'completed' ? 'text-[var(--text-primary)] font-medium' :
                      state === 'blocked' ? 'text-[var(--status-error)] font-bold' :
                      state === 'cancelled' ? 'text-[var(--text-tertiary)] line-through font-medium' :
                      'text-[var(--text-secondary)] font-medium'
                    )}>
                      {stage.label}
                    </p>
                    {state === 'current' && (
                      <p className="text-[11px] uppercase tracking-wider font-semibold text-[var(--brand-primary)] mt-1">
                        Etapa actual
                      </p>
                    )}
                  </div>
                </li>
              );
            })}
          </ol>
        </section>

        {/* Right column: next milestone + recent activity */}
        <aside className="w-full lg:w-80 flex-shrink-0 space-y-6 min-w-0">
          <div className="bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6">
            <h3 className="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider mb-3">
              Siguiente hito
            </h3>
            <p className="text-sm font-semibold text-[var(--text-primary)] leading-snug break-words">
              {nextMilestone(status, hasFailedTasks)}
            </p>
            {isOperative && (
              <p className="text-xs text-[var(--status-success)] mt-2 font-medium">
                El alta operativa fue completada.
              </p>
            )}
          </div>

          <div className="bg-[var(--bg-elevated)] rounded-xl border border-[var(--border-subtle)] p-6">
            <div className="flex items-baseline justify-between mb-4 gap-3 flex-wrap">
              <h3 className="text-xs font-semibold text-[var(--text-tertiary)] uppercase tracking-wider">
                Actividad reciente
              </h3>
              {onOpenAudit ? (
                <button
                  type="button"
                  onClick={onOpenAudit}
                  className="text-[10px] font-semibold text-[var(--brand-primary)] inline-flex items-center gap-1 uppercase tracking-wider hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand-primary)] rounded"
                >
                  Ver auditoría completa <ArrowRight className="w-3 h-3" aria-hidden="true" />
                </button>
              ) : (
                <span className="text-[10px] text-[var(--text-tertiary)] inline-flex items-center gap-1 uppercase tracking-wider">
                  Disponible en la pestaña Auditoría
                </span>
              )}
            </div>

            {sortedEvents.length === 0 ? (
              <p className="text-sm text-[var(--text-tertiary)]">Sin actividad registrada</p>
            ) : (
              <ul className="relative pl-5">
                {sortedEvents.map((event, i, arr) => (
                  <li key={event.id} className="relative pb-4 last:pb-0">
                    {i < arr.length - 1 && (
                      <span
                        aria-hidden="true"
                        className="absolute bg-[var(--border-subtle)]"
                        style={{ left: '-13px', top: '13px', bottom: '-4px', width: '1px' }}
                      />
                    )}
                    <span
                      aria-hidden="true"
                      className="absolute z-10 rounded-full border-2 border-[var(--border-default)] bg-[var(--bg-base)]"
                      style={{ left: '-17px', top: '4px', width: '8px', height: '8px' }}
                    />
                    <p className="text-sm font-medium text-[var(--text-primary)] break-words">
                      {actionLabel(event.action)}
                    </p>
                    <div className="flex items-center gap-2 mt-1 flex-wrap">
                      <span className={cn(
                        'text-[10px] font-semibold px-1.5 py-0.5 rounded uppercase tracking-wide',
                        actorBadgeClass(event)
                      )}>
                        {actorBadgeLabel(event)}
                      </span>
                      <span className="text-xs text-[var(--text-tertiary)]">
                        {formatRelativeTime(event.timestamp)}
                      </span>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </aside>
      </div>
    </div>
  );
}
