// src/components/rrhh/CaseActions.tsx
import { useState } from 'react';
import { useStore } from '../../store';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';
import { Textarea } from '../ui/Input';
import {
  Send,
  Play,
  Check,
  AlertTriangle,
  Lock,
  Unlock,
  XCircle,
  ArrowRight,
  MessageSquare,
} from 'lucide-react';

export function CaseActions() {
  const {
    getSelectedCase,
    sendCandidateForm,
    startReview,
    requestCorrection,
    approve,
    activate,
    block,
    unblock,
    cancel,
    addToast,
  } = useStore();

  const [showCorrectionModal, setShowCorrectionModal] = useState(false);
  const [showBlockModal, setShowBlockModal] = useState(false);
  const [correctionNote, setCorrectionNote] = useState('');
  const [blockReason, setBlockReason] = useState('');

  const selectedCase = getSelectedCase();
  if (!selectedCase) return null;

  const { status, id } = selectedCase;

  const handleSendForm = () => {
    sendCandidateForm(id);
  };

  const handleStartReview = () => {
    startReview(id);
  };

  const handleCorrection = () => {
    if (!correctionNote.trim()) {
      addToast({ type: 'warning', title: 'Indicá el motivo de la corrección.' });
      return;
    }
    requestCorrection(id, correctionNote);
    setShowCorrectionModal(false);
    setCorrectionNote('');
  };

  const handleApprove = () => {
    approve(id);
  };

  const handleActivate = () => {
    activate(id);
  };

  const handleBlock = () => {
    if (!blockReason.trim()) {
      addToast({ type: 'warning', title: 'Indicá el motivo del bloqueo.' });
      return;
    }
    block(id, blockReason);
    setShowBlockModal(false);
    setBlockReason('');
  };

  const handleUnblock = () => {
    unblock(id);
  };

  const handleCancelar = () => {
    if (confirm('¿Seguro que querés cancelar este caso? Esta acción no se puede deshacer.')) {
      cancel(id);
    }
  };

  return (
    <>
      <div className="px-4 lg:px-6 py-4 border-t border-[var(--border-subtle)] bg-[var(--bg-subtle)] safe-bottom">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="text-xs text-[var(--text-tertiary)] hidden lg:block">
            {status === 'draft' && 'El caso está en borrador. Enviá el formulario al candidato para continuar.'}
            {status === 'candidate_invited' && 'Formulario enviado. Esperando respuesta del candidato.'}
            {status === 'candidate_submitted' && 'El candidato envió sus datos. Listo para revisión.'}
            {status === 'hr_review' && 'Revisá los detalles del candidato y aprobá, solicitá corrección o bloqueá el caso.'}
            {status === 'ready_to_activate' && 'Perfil verificado. El caso está listo para activación operativa.'}
            {status === 'active_pending_automation' && 'Tareas automáticas de directorio y accesos en curso...'}
            {status === 'operative' && 'Onboarding completado. El colaborador está activo.'}
            {status === 'blocked' && `Bloqueado: ${selectedCase.blockReason || 'Sin motivo especificado'}`}
            {status === 'cancelled' && 'Este caso fue cancelado.'}
          </div>

          <div className="flex items-center gap-2 lg:gap-3 flex-wrap">
            {status === 'draft' && (
              <Button onClick={handleSendForm} className="min-h-[44px]">
                <Send className="w-4 h-4" />
                Enviar formulario
              </Button>
            )}

            {status === 'candidate_submitted' && (
              <Button onClick={handleStartReview} className="min-h-[44px]">
                <ArrowRight className="w-4 h-4" />
                Iniciar revisión
              </Button>
            )}

            {status === 'hr_review' && (
              <>
                <Button variant="ghost" onClick={() => setShowBlockModal(true)} className="min-h-[44px]">
                  <Lock className="w-4 h-4" />
                  Bloquear caso
                </Button>
                <Button variant="secondary" onClick={() => setShowCorrectionModal(true)} className="min-h-[44px]">
                  <MessageSquare className="w-4 h-4" />
                  Solicitar corrección
                </Button>
                <Button onClick={handleApprove} className="min-h-[44px]">
                  <Check className="w-4 h-4" />
                  Aprobar caso
                </Button>
              </>
            )}

            {status === 'ready_to_activate' && (
              <Button onClick={handleActivate} className="min-h-[44px]">
                <Play className="w-4 h-4" />
                Activar onboarding
              </Button>
            )}

            {status === 'blocked' && (
              <>
                <Button variant="danger" size="sm" onClick={handleCancelar} className="min-h-[44px]">
                  <XCircle className="w-4 h-4" />
                  Cancelar caso
                </Button>
                <Button onClick={handleUnblock} className="min-h-[44px]">
                  <Unlock className="w-4 h-4" />
                  Desbloquear caso
                </Button>
              </>
            )}

            {(status === 'draft' || status === 'candidate_invited' || status === 'hr_review') && (
              <Button variant="ghost" size="sm" onClick={handleCancelar} className="min-h-[44px]">
                <XCircle className="w-4 h-4" />
                Cancelar caso
              </Button>
            )}
          </div>
        </div>
      </div>

      {/* Correction Modal */}
      <Modal
        isOpen={showCorrectionModal}
        onClose={() => setShowCorrectionModal(false)}
        title="Solicitar corrección de onboarding"
      >
        <div className="space-y-4">
          <p className="text-sm text-[var(--text-secondary)]">
            Se enviará una solicitud de corrección al candidato con este comentario:
          </p>
          <Textarea
            label="Motivo de corrección"
            value={correctionNote}
            onChange={(e) => setCorrectionNote(e.target.value)}
            placeholder="Ej.: el número de CUIT tiene un dígito inválido, por favor volvé a cargar el documento..."
            rows={4}
          />
          <div className="flex justify-end gap-3">
            <Button variant="secondary" onClick={() => setShowCorrectionModal(false)} className="min-h-[44px]">
              Cancelar
            </Button>
            <Button onClick={handleCorrection} className="min-h-[44px]">
              <AlertTriangle className="w-4 h-4" />
              Enviar solicitud
            </Button>
          </div>
        </div>
      </Modal>

      {/* Block Modal */}
      <Modal
        isOpen={showBlockModal}
        onClose={() => setShowBlockModal(false)}
        title="Bloquear caso de onboarding"
      >
        <div className="space-y-4">
          <p className="text-sm text-[var(--text-secondary)]">
            El caso quedará bloqueado hasta que un operador lo desbloquee manualmente.
          </p>
          <Textarea
            label="Motivo del bloqueo"
            value={blockReason}
            onChange={(e) => setBlockReason(e.target.value)}
            placeholder="Ej.: verificación pendiente o documentación ilegible..."
            rows={4}
          />
          <div className="flex justify-end gap-3">
            <Button variant="secondary" onClick={() => setShowBlockModal(false)} className="min-h-[44px]">
              Cancelar
            </Button>
            <Button variant="danger" onClick={handleBlock} className="min-h-[44px]">
              <Lock className="w-4 h-4" />
              Bloquear caso
            </Button>
          </div>
        </div>
      </Modal>
    </>
  );
}

// apps/web-angular/src/app/onboarding/components/case-actions/case-actions.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { OnboardingMockService } from '../../services/onboarding-mock.service';
import { ModalComponent } from '../../../shared/components/modal/modal.component';

@Component({
  selector: 'app-case-actions',
  standalone: true,
  imports: [ModalComponent, FormsModule],
  template: `
    @if (svc.selectedCase(); as c) {
      <div class="px-4 lg:px-6 py-4 border-t border-[var(--border-subtle)] bg-[var(--bg-subtle)]">
        <div class="flex items-center justify-between gap-3 flex-wrap">
          <div class="text-xs text-[var(--text-tertiary)] hidden lg:block">
            @switch (c.status) {
              @case ('draft')                      { El caso está en borrador. Enviá el formulario al candidato para continuar. }
              @case ('candidate_invited')          { Formulario enviado. Esperando respuesta del candidato. }
              @case ('candidate_submitted')        { El candidato envió sus datos. Listo para revisión. }
              @case ('hr_review')                  { Revisá los detalles del candidato y aprobá, solicitá corrección o bloqueá el caso. }
              @case ('ready_to_activate')          { Perfil verificado. El caso está listo para activación operativa. }
              @case ('active_pending_automation')  { Tareas automáticas de directorio y accesos en curso... }
              @case ('operative')                  { Onboarding completado. El colaborador está activo. }
              @case ('blocked')                    { Bloqueado: {{ c.blockReason || 'Sin motivo especificado' }} }
              @case ('cancelled')                  { Este caso fue cancelado. }
            }
          </div>

          <div class="flex items-center gap-2 lg:gap-3 flex-wrap">
            @if (c.status === 'draft') {
              <button (click)="svc.sendCandidateForm(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] min-h-[44px]">
                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
                Enviar formulario
              </button>
            }

            @if (c.status === 'candidate_submitted') {
              <button (click)="svc.startReview(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] min-h-[44px]">
                Iniciar revisión
              </button>
            }

            @if (c.status === 'hr_review') {
              <button (click)="showBlockModal.set(true)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--text-secondary)] border border-[var(--border-default)] hover:bg-[var(--bg-subtle)] min-h-[44px]">
                Bloquear caso
              </button>
              <button (click)="showCorrectionModal.set(true)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--text-primary)] bg-[var(--bg-elevated)] border border-[var(--border-default)] hover:bg-[var(--bg-subtle)] min-h-[44px]">
                Solicitar corrección
              </button>
              <button (click)="svc.approve(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] min-h-[44px]">
                Aprobar caso
              </button>
            }

            @if (c.status === 'ready_to_activate') {
              <button (click)="svc.activate(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] min-h-[44px]">
                Activar onboarding
              </button>
            }

            @if (c.status === 'blocked') {
              <button (click)="svc.cancel(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--status-error)] hover:opacity-90 min-h-[44px]">
                Cancelar caso
              </button>
              <button (click)="svc.unblock(c.id)" class="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)] min-h-[44px]">
                Desbloquear caso
              </button>
            }

            @if (c.status === 'draft' || c.status === 'candidate_invited' || c.status === 'hr_review') {
              <button (click)="handleCancel(c.id)" class="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold text-[var(--text-tertiary)] hover:text-[var(--status-error)] hover:bg-[var(--status-error-subtle)] min-h-[44px]">
                Cancelar caso
              </button>
            }
          </div>
        </div>
      </div>

      <!-- Correction Modal -->
      <app-modal [isOpen]="showCorrectionModal()" title="Solicitar corrección de onboarding" (onClose)="showCorrectionModal.set(false)">
        <div class="space-y-4">
          <p class="text-sm text-[var(--text-secondary)]">Se enviará una solicitud de corrección al candidato con este comentario:</p>
          <div>
            <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Motivo de corrección</label>
            <textarea [(ngModel)]="correctionNote" rows="4" placeholder="Ej.: el número de CUIT tiene un dígito inválido..."
              class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)] resize-none"></textarea>
          </div>
          <div class="flex justify-end gap-3">
            <button (click)="showCorrectionModal.set(false)" class="px-4 py-2 rounded-lg text-sm font-semibold border border-[var(--border-default)] text-[var(--text-secondary)]">Cancelar</button>
            <button (click)="handleCorrection(c.id)" class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)]">Enviar solicitud</button>
          </div>
        </div>
      </app-modal>

      <!-- Block Modal -->
      <app-modal [isOpen]="showBlockModal()" title="Bloquear caso de onboarding" (onClose)="showBlockModal.set(false)">
        <div class="space-y-4">
          <p class="text-sm text-[var(--text-secondary)]">El caso quedará bloqueado hasta que un operador lo desbloquee manualmente.</p>
          <div>
            <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Motivo del bloqueo</label>
            <textarea [(ngModel)]="blockReason" rows="4" placeholder="Ej.: verificación pendiente o documentación ilegible..."
              class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)] resize-none"></textarea>
          </div>
          <div class="flex justify-end gap-3">
            <button (click)="showBlockModal.set(false)" class="px-4 py-2 rounded-lg text-sm font-semibold border border-[var(--border-default)] text-[var(--text-secondary)]">Cancelar</button>
            <button (click)="handleBlock(c.id)" class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--status-error)] hover:opacity-90">Bloquear caso</button>
          </div>
        </div>
      </app-modal>
    }
  `,
})
export class CaseActionsComponent {
  readonly svc = inject(OnboardingMockService);
  readonly showCorrectionModal = signal(false);
  readonly showBlockModal = signal(false);
  correctionNote = '';
  blockReason = '';

  handleCorrection(caseId: string): void {
    if (!this.correctionNote.trim()) { this.svc.addToast('warning', 'Indicá el motivo de la corrección.'); return; }
    this.svc.requestCorrection(caseId, this.correctionNote);
    this.showCorrectionModal.set(false);
    this.correctionNote = '';
  }

  handleBlock(caseId: string): void {
    if (!this.blockReason.trim()) { this.svc.addToast('warning', 'Indicá el motivo del bloqueo.'); return; }
    this.svc.block(caseId, this.blockReason);
    this.showBlockModal.set(false);
    this.blockReason = '';
  }

  handleCancel(caseId: string): void {
    if (confirm('¿Seguro que querés cancelar este caso? Esta acción no se puede deshacer.')) {
      this.svc.cancel(caseId);
    }
  }
}
