// src/components/candidate/CandidateWizard.tsx
import { useState, useEffect } from 'react';
import { useStore } from '../../store';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Select } from '../ui/Select';
import { Clock, CheckCircle, AlertTriangle, ChevronLeft, ChevronRight, Send, Plus, Trash2 } from 'lucide-react';
import { TAX_ID_TYPES, Reference } from '../../types';
import { cn } from '../../utils/cn';
import { v4 as uuidv4 } from 'uuid';

interface CandidateWizardProps {
  token: string;
}

const STEPS = [
  { id: 1, title: 'Identificación fiscal' },
  { id: 2, title: 'Método de cobro' },
  { id: 3, title: 'Referencias' },
  { id: 4, title: 'Archivos' },
];

export function CandidateWizard({ token }: CandidateWizardProps) {
  const { getCaseByToken, updateCandidateData, submitCandidateForm, addToast } = useStore();
  const caseData = getCaseByToken(token);

  const [step, setStep] = useState(1);

  // Redirect to correct step if candidate has progress
  useEffect(() => {
    if (caseData?.candidateData?.currentStep) {
      setStep(caseData.candidateData.currentStep);
    }
  }, [caseData?.candidateData?.currentStep]);

  if (!caseData) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-6">
        <AlertTriangle className="w-16 h-16 text-[var(--status-warning)] mb-4" />
        <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-2">
          Link inválido o expirado
        </h2>
        <p className="text-[var(--text-secondary)]">
          Contactá a RRHH para recibir un nuevo link de formulario.
        </p>
      </div>
    );
  }

  if (caseData.candidateData?.submittedAt) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-6">
        <CheckCircle className="w-16 h-16 text-[var(--status-success)] mb-4" />
        <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-2">
          ¡Formulario enviado!
        </h2>
        <p className="text-[var(--text-secondary)]">
          Gracias por completar tus datos. Ya podés cerrar esta ventana.
        </p>
      </div>
    );
  }

  if (caseData.status !== 'candidate_invited') {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center px-6">
        <Clock className="w-16 h-16 text-[var(--text-tertiary)] mb-4" />
        <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-2">
          Formulario no disponible
        </h2>
        <p className="text-[var(--text-secondary)]">
          Este formulario ya fue procesado o no está disponible en este momento.
        </p>
      </div>
    );
  }

  const { employee, candidateData, correctionNote } = caseData;
  const data = candidateData || {
    taxIdType: '',
    taxIdValue: '',
    paymentMethod: '',
    cbu: '',
    bankName: '',
    accountNumber: '',
    swift: '',
    beneficiaryAddress: '',
    needsW8: false,
    walletType: '',
    walletAddress: '',
    hasQrBinance: false,
    references: [],
    files: [],
    currentStep: 1,
    completedSteps: [],
    submittedAt: null,
    consolidated: false,
  };

  const updateData = (updates: Partial<typeof data>) => {
    updateCandidateData(caseData.id, updates);
  };

  const canProceed = () => {
    if (step === 1) {
      return data.taxIdType && data.taxIdValue;
    }
    if (step === 2) {
      if (!data.paymentMethod) return false;
      if (data.paymentMethod === 'CBU' && !data.cbu) return false;
      if (data.paymentMethod === 'WIRE' && (!data.bankName || !data.accountNumber || !data.swift)) return false;
      if (data.paymentMethod === 'CRYPTO' && (!data.walletType || !data.walletAddress)) return false;
      return true;
    }
    if (step === 3) {
      return data.references?.length > 0 && data.references.every((r: Reference) => r.fullName && r.email);
    }
    return true;
  };

  const goNext = () => {
    if (!canProceed()) {
      addToast({ type: 'warning', title: 'Completá los campos requeridos' });
      return;
    }
    const completedSteps = [...(data.completedSteps || [])];
    if (!completedSteps.includes(step)) {
      completedSteps.push(step);
    }
    updateData({ currentStep: step + 1, completedSteps });
    setStep(step + 1);
  };

  const goBack = () => {
    updateData({ currentStep: step - 1 });
    setStep(step - 1);
  };

  const handleSubmit = () => {
    submitCandidateForm(caseData.id);
    addToast({ type: 'success', title: '¡Formulario enviado!' });
  };

  // Check if step 4 is needed
  const needsFiles = data.needsW8 || data.hasQrBinance;
  const maxStep = needsFiles ? 4 : 3;
  const isLastStep = step === maxStep;

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-6 py-4 border-b border-[var(--border-subtle)]">
        <div className="text-center mb-4">
          <h1 className="text-2xl font-bold text-[var(--text-primary)]">
            ¡Bienvenido/a a Zafirus, {employee.name}!
          </h1>
          <p className="text-[var(--text-secondary)] mt-1">
            Completá los siguientes datos para continuar con tu onboarding
          </p>
        </div>

        {/* Correction banner */}
        {correctionNote && (
          <div className="bg-[var(--status-warning-subtle)] border border-[var(--status-warning)] rounded-lg px-4 py-3 mb-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-[var(--status-warning)] flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-[var(--status-warning)]">
                  RRHH solicitó las siguientes correcciones:
                </p>
                <p className="text-sm text-[var(--text-primary)] mt-1">{correctionNote}</p>
              </div>
            </div>
          </div>
        )}

        {/* Stepper */}
        <div className="flex items-center justify-center gap-2">
          {STEPS.filter(s => s.id <= maxStep).map((s, i) => (
            <div key={s.id} className="flex items-center">
              <div
                className={cn(
                  'w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold transition-colors',
                  step === s.id && 'bg-[var(--brand-primary)] text-white',
                  step > s.id && 'bg-[var(--status-success-subtle)] text-[var(--status-success)] border border-[var(--status-success)]',
                  step < s.id && 'bg-[var(--bg-elevated)] text-[var(--text-tertiary)] border border-[var(--border-default)]'
                )}
              >
                {step > s.id ? <CheckCircle className="w-4 h-4" /> : s.id}
              </div>
              {i < STEPS.filter(s => s.id <= maxStep).length - 1 && (
                <div
                  className={cn(
                    'w-12 h-0.5 mx-2',
                    step > s.id ? 'bg-[var(--status-success)]' : 'bg-[var(--border-default)]'
                  )}
                />
              )}
            </div>
          ))}
        </div>
        <p className="text-center text-sm text-[var(--text-secondary)] mt-2">
          Paso {step} de {maxStep}: {STEPS.find(s => s.id === step)?.title}
        </p>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6">
        <div className="max-w-lg mx-auto">
          {step === 1 && (
            <Step1
              data={data}
              updateData={updateData}
            />
          )}
          {step === 2 && (
            <Step2
              data={data}
              updateData={updateData}
            />
          )}
          {step === 3 && (
            <Step3
              data={data}
              updateData={updateData}
            />
          )}
          {step === 4 && needsFiles && (
            <Step4
              data={data}
              updateData={updateData}
            />
          )}
        </div>
      </div>

      {/* Footer */}
      <div className="px-6 py-4 border-t border-[var(--border-subtle)] bg-[var(--bg-subtle)]">
        <div className="max-w-lg mx-auto flex items-center justify-between">
          <Button
            variant="ghost"
            onClick={goBack}
            disabled={step === 1}
          >
            <ChevronLeft className="w-4 h-4" />
            Atrás
          </Button>

          {isLastStep ? (
            <Button onClick={handleSubmit}>
              <Send className="w-4 h-4" />
              Enviar formulario
            </Button>
          ) : (
            <Button onClick={goNext}>
              Siguiente
              <ChevronRight className="w-4 h-4" />
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}

// Step 1: Tax ID
function Step1({ data, updateData }: { data: any; updateData: (d: any) => void }) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-2">
          Identificación fiscal
        </h2>
        <p className="text-sm text-[var(--text-secondary)]">
          Indicá tu identificador fiscal principal.
        </p>
      </div>

      <Select
        label="Tipo de identificador"
        value={data.taxIdType}
        onChange={(e) => updateData({ taxIdType: e.target.value })}
        options={TAX_ID_TYPES.map(t => ({ value: t.code, label: t.label }))}
        placeholder="Seleccioná un tipo"
      />

      <Input
        label="Número"
        value={data.taxIdValue}
        onChange={(e) => updateData({ taxIdValue: e.target.value })}
        placeholder={TAX_ID_TYPES.find(t => t.code === data.taxIdType)?.mask || 'Ingresá el número'}
        helper="Solo validamos el formato, no contra APIs externas."
      />
    </div>
  );
}

// Step 2: Payment Method
function Step2({ data, updateData }: { data: any; updateData: (d: any) => void }) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-2">
          Método de cobro
        </h2>
        <p className="text-sm text-[var(--text-secondary)]">
          ¿Cómo preferís recibir tus pagos? Esta elección es independiente de tu país de residencia.
        </p>
      </div>

      <div className="space-y-3">
        <PaymentOption
          selected={data.paymentMethod === 'CBU'}
          onSelect={() => updateData({ paymentMethod: 'CBU', needsW8: false, hasQrBinance: false })}
          icon="💳"
          title="CBU (Argentina)"
          description="Cuenta bancaria argentina"
        />
        <PaymentOption
          selected={data.paymentMethod === 'WIRE'}
          onSelect={() => updateData({ paymentMethod: 'WIRE', hasQrBinance: false })}
          icon="🌐"
          title="Transferencia internacional"
          description="Banco extranjero vía SWIFT"
        />
        <PaymentOption
          selected={data.paymentMethod === 'CRYPTO'}
          onSelect={() => updateData({ paymentMethod: 'CRYPTO', needsW8: false })}
          icon="₿"
          title="Crypto (Binance)"
          description="Wallet de criptomonedas"
        />
      </div>

      <div className={cn('payment-fields-enter', data.paymentMethod === 'CBU' && 'visible')}>
        <div className="pt-2">
          <Input
            label="CBU"
            value={data.cbu}
            onChange={(e) => updateData({ cbu: e.target.value })}
            placeholder="22 dígitos"
            helper="Encontrás tu CBU en tu homebanking o app del banco."
          />
        </div>
      </div>

      <div className={cn('payment-fields-enter', data.paymentMethod === 'WIRE' && 'visible')}>
        <div className="space-y-4 pt-2">
          <Input
            label="Nombre del banco"
            value={data.bankName}
            onChange={(e) => updateData({ bankName: e.target.value })}
          />
          <Input
            label="Número de cuenta"
            value={data.accountNumber}
            onChange={(e) => updateData({ accountNumber: e.target.value })}
          />
          <Input
            label="Código SWIFT"
            value={data.swift}
            onChange={(e) => updateData({ swift: e.target.value })}
          />
          <Input
            label="Dirección del beneficiario"
            value={data.beneficiaryAddress}
            onChange={(e) => updateData({ beneficiaryAddress: e.target.value })}
          />
          <label className="flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={data.needsW8}
              onChange={(e) => updateData({ needsW8: e.target.checked })}
              className="w-4 h-4 rounded border-[var(--border-default)] bg-[var(--bg-elevated)]"
            />
            <span className="text-sm text-[var(--text-primary)]">
              Necesito completar formulario W-8 (residentes fuera de USA)
            </span>
          </label>
        </div>
      </div>

      <div className={cn('payment-fields-enter', data.paymentMethod === 'CRYPTO' && 'visible')}>
        <div className="space-y-4 pt-2">
          <Select
            label="Tipo de wallet"
            value={data.walletType}
            onChange={(e) => updateData({ walletType: e.target.value })}
            options={[
              { value: 'BINANCE', label: 'Binance' },
              { value: 'OTHER', label: 'Otra wallet' },
            ]}
            placeholder="Seleccioná..."
          />
          <Input
            label="Dirección de wallet / Binance ID"
            value={data.walletAddress}
            onChange={(e) => updateData({ walletAddress: e.target.value })}
          />
          <label className="flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={data.hasQrBinance}
              onChange={(e) => updateData({ hasQrBinance: e.target.checked })}
              className="w-4 h-4 rounded border-[var(--border-default)] bg-[var(--bg-elevated)]"
            />
            <span className="text-sm text-[var(--text-primary)]">
              Voy a subir QR de Binance
            </span>
          </label>
        </div>
      </div>
    </div>
  );
}

function PaymentOption({ selected, onSelect, icon, title, description }: {
  selected: boolean;
  onSelect: () => void;
  icon: string;
  title: string;
  description: string;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={cn(
        'w-full flex items-center gap-4 p-4 rounded-lg border text-left transition-[border-color,background-color] duration-150',
        selected
          ? 'border-[var(--brand-primary)] bg-[var(--brand-primary-subtle)]'
          : 'border-[var(--border-default)] hover:border-[var(--border-strong)] bg-[var(--bg-elevated)]'
      )}
    >
      <span className="text-2xl">{icon}</span>
      <div>
        <p className="text-sm font-medium text-[var(--text-primary)]">{title}</p>
        <p className="text-xs text-[var(--text-secondary)]">{description}</p>
      </div>
      <div className={cn(
        'ml-auto w-5 h-5 rounded-full border-2 flex items-center justify-center',
        selected
          ? 'border-[var(--brand-primary)] bg-[var(--brand-primary)]'
          : 'border-[var(--border-default)]'
      )}>
        {selected && <CheckCircle className="w-3 h-3 text-white" />}
      </div>
    </button>
  );
}

// Step 3: References
function Step3({ data, updateData }: { data: any; updateData: (d: any) => void }) {
  const references: Reference[] = data.references || [];

  const addReference = () => {
    updateData({
      references: [...references, {
        id: uuidv4(),
        fullName: '',
        relationship: '',
        company: '',
        email: '',
        phone: '',
      }]
    });
  };

  // Auto-add first reference if none exist
  useEffect(() => {
    if (references.length === 0) {
      addReference();
    }
  }, []);

  const updateReference = (id: string, updates: Partial<Reference>) => {
    updateData({
      references: references.map(r => r.id === id ? { ...r, ...updates } : r)
    });
  };

  const removeReference = (id: string) => {
    updateData({
      references: references.filter(r => r.id !== id)
    });
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-2">
          Referencias laborales
        </h2>
        <p className="text-sm text-[var(--text-secondary)]">
          Agregá al menos una referencia laboral. Máximo 3.
        </p>
      </div>

      {references.map((ref, index) => (
        <div key={ref.id} className="bg-[var(--bg-elevated)] rounded-lg p-4 border border-[var(--border-subtle)]">
          <div className="flex items-center justify-between mb-4">
            <span className="text-sm font-medium text-[var(--text-primary)]">
              Referencia {index + 1}
            </span>
            {references.length > 1 && (
              <button
                onClick={() => removeReference(ref.id)}
                className="p-1 rounded text-[var(--text-tertiary)] hover:text-[var(--status-error)] hover:bg-[var(--status-error-subtle)]"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>
          <div className="grid grid-cols-2 gap-4">
            <Input
              label="Nombre completo"
              value={ref.fullName}
              onChange={(e) => updateReference(ref.id, { fullName: e.target.value })}
            />
            <Input
              label="Relación"
              value={ref.relationship}
              onChange={(e) => updateReference(ref.id, { relationship: e.target.value })}
              placeholder="ej: Jefe directo"
            />
            <Input
              label="Empresa"
              value={ref.company}
              onChange={(e) => updateReference(ref.id, { company: e.target.value })}
            />
            <Input
              label="Email"
              type="email"
              value={ref.email}
              onChange={(e) => updateReference(ref.id, { email: e.target.value })}
            />
            <Input
              label="Teléfono"
              value={ref.phone}
              onChange={(e) => updateReference(ref.id, { phone: e.target.value })}
            />
          </div>
        </div>
      ))}

      {references.length < 3 && (
        <Button variant="secondary" onClick={addReference} className="w-full">
          <Plus className="w-4 h-4" />
          Agregar referencia
        </Button>
      )}

      {references.length === 0 && (
        <p className="text-sm text-[var(--status-warning)] text-center">
          Agregá al menos una referencia para continuar.
        </p>
      )}
    </div>
  );
}

// Step 4: Files
function Step4({ data, updateData }: { data: any; updateData: (d: any) => void }) {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-2">
          Archivos
        </h2>
        <p className="text-sm text-[var(--text-secondary)]">
          Subí los archivos que correspondan según tu método de cobro.
        </p>
      </div>

      {data.needsW8 && (
        <div className="bg-[var(--bg-elevated)] rounded-lg p-6 border border-dashed border-[var(--border-default)] text-center">
          <p className="text-sm font-medium text-[var(--text-primary)] mb-2">
            Formulario W-8 (PDF)
          </p>
          <p className="text-xs text-[var(--text-tertiary)] mb-4">
            Requerido para transferencias internacionales
          </p>
          <input
            type="file"
            accept=".pdf"
            className="hidden"
            id="w8-upload"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                updateData({
                  files: [...(data.files || []), {
                    id: uuidv4(),
                    fileType: 'w8',
                    name: file.name,
                    sizeBytes: file.size,
                  }]
                });
              }
            }}
          />
          <label
            htmlFor="w8-upload"
            className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--brand-primary)] text-white rounded-lg cursor-pointer hover:bg-[var(--brand-primary-hover)] transition-colors"
          >
            <Plus className="w-4 h-4" />
            Subir W-8
          </label>
        </div>
      )}

      {data.hasQrBinance && (
        <div className="bg-[var(--bg-elevated)] rounded-lg p-6 border border-dashed border-[var(--border-default)] text-center">
          <p className="text-sm font-medium text-[var(--text-primary)] mb-2">
            QR de Binance (PNG/JPG)
          </p>
          <p className="text-xs text-[var(--text-tertiary)] mb-4">
            Screenshot del QR de tu wallet
          </p>
          <input
            type="file"
            accept="image/png,image/jpeg"
            className="hidden"
            id="qr-upload"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) {
                updateData({
                  files: [...(data.files || []), {
                    id: uuidv4(),
                    fileType: 'qr_binance',
                    name: file.name,
                    sizeBytes: file.size,
                  }]
                });
              }
            }}
          />
          <label
            htmlFor="qr-upload"
            className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--brand-primary)] text-white rounded-lg cursor-pointer hover:bg-[var(--brand-primary-hover)] transition-colors"
          >
            <Plus className="w-4 h-4" />
            Subir QR
          </label>
        </div>
      )}

      {data.files?.length > 0 && (
        <div className="space-y-2">
          <p className="text-sm font-medium text-[var(--text-primary)]">Archivos subidos:</p>
          {data.files.map((file: any) => (
            <div key={file.id} className="flex items-center justify-between bg-[var(--bg-surface)] rounded px-3 py-2">
              <span className="text-sm text-[var(--text-primary)]">{file.name}</span>
              <button
                onClick={() => updateData({ files: data.files.filter((f: any) => f.id !== file.id) })}
                className="p-1 text-[var(--text-tertiary)] hover:text-[var(--status-error)]"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// apps/web-angular/src/app/onboarding/candidate/candidate-wizard/candidate-wizard.component.ts
import { Component, inject, signal, Input, Output, EventEmitter } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { OnboardingMockService } from '../../services/onboarding-mock.service';
import { ZafirusLogoComponent } from '../../../shared/components/zafirus-logo/zafirus-logo.component';
import { CandidateData, Reference, TAX_ID_TYPES } from '../../models/onboarding-case.model';

const STEPS = [
  { id: 1, title: 'Identificación fiscal' },
  { id: 2, title: 'Datos de cobro' },
  { id: 3, title: 'Referencias' },
  { id: 4, title: 'Archivos' },
];

@Component({
  selector: 'app-candidate-wizard',
  standalone: true,
  imports: [FormsModule, ZafirusLogoComponent],
  template: `
    @if (svc.selectedCase(); as c) {
      @if (c.candidateData; as cd) {
        @if (cd.submittedAt) {
          <!-- Submitted state -->
          <div class="h-full flex flex-col items-center justify-center text-center px-6 py-12 bg-[var(--bg-subtle)]">
            <svg class="w-16 h-16 text-[var(--status-success)] mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
            <h2 class="text-lg font-bold text-[var(--text-primary)] mb-2">Formulario enviado</h2>
            <p class="text-sm text-[var(--text-secondary)] max-w-sm">
              RRHH revisará tus datos y continuará con el alta operativa.
            </p>
          </div>
        } @else {
          <div class="max-w-xl mx-auto px-4 py-6">
            <!-- Welcome header -->
            <div class="flex flex-col items-center justify-center pt-4 pb-4 text-center mb-6">
              <div class="mb-4">
                <app-zafirus-logo [size]="40" />
              </div>
              <h1 class="text-2xl font-bold text-[var(--text-primary)] tracking-tight">Bienvenida/o a Zafirus</h1>
              <p class="text-sm font-medium text-[var(--text-secondary)] mt-2 max-w-sm leading-relaxed">
                Hola, {{ c.employee.name }}. Completá tus datos para avanzar con el alta operativa.
              </p>
            </div>

            <!-- Correction notice -->
            @if (c.correctionNote) {
              <div class="bg-[var(--status-warning-subtle)] border rounded-xl p-5 mb-6 text-left shadow-sm" style="border-color: rgba(217,119,6,0.2)">
                <h3 class="text-sm font-bold text-[var(--status-warning)] mb-1.5">RRHH solicitó una corrección</h3>
                <p class="text-sm text-[var(--text-primary)] font-medium mb-3">Revisá el comentario y actualizá los datos necesarios.</p>
                <div class="bg-[var(--bg-base)] p-3 rounded-lg border border-[var(--border-subtle)] text-sm text-[var(--text-secondary)]">{{ c.correctionNote }}</div>
              </div>
            }

            <!-- Step indicators -->
            <div class="flex items-center justify-center gap-1 sm:gap-3 mb-8">
              @for (step of steps; track step.id; let i = $index) {
                <div class="flex items-center">
                  <div class="flex flex-col items-center gap-1.5">
                    <div class="w-7 h-7 sm:w-8 sm:h-8 rounded-full flex items-center justify-center text-xs font-bold border"
                      [class]="cd.currentStep === step.id ? 'bg-[var(--brand-primary)] text-white border-[var(--brand-primary)] shadow-sm'
                        : cd.completedSteps.includes(step.id) ? 'bg-[var(--status-success-subtle)] text-[var(--status-success)] border-[var(--status-success)]'
                        : 'bg-[var(--bg-elevated)] text-[var(--text-tertiary)] border-[var(--border-default)]'"
                    >
                      @if (cd.completedSteps.includes(step.id)) {
                        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                      } @else { {{ i + 1 }} }
                    </div>
                    <span class="text-[9px] sm:text-[10px] font-bold uppercase tracking-wider hidden sm:block"
                      [class]="cd.currentStep === step.id ? 'text-[var(--brand-primary)]' : cd.completedSteps.includes(step.id) ? 'text-[var(--text-primary)]' : 'text-[var(--text-tertiary)]'"
                    >{{ step.title }}</span>
                  </div>
                  @if (i < steps.length - 1) {
                    <div class="w-3 sm:w-6 h-[2px] mx-1 sm:mx-2 rounded-full"
                      [class]="cd.completedSteps.includes(step.id) ? 'bg-[var(--status-success)]' : 'bg-[var(--border-subtle)]'"></div>
                  }
                </div>
              }
            </div>

            <!-- Step content -->
            <div class="bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-2xl p-5 sm:p-8 shadow-sm mb-6">
              @switch (cd.currentStep) {
                @case (1) {
                  <h2 class="text-xl font-bold text-[var(--text-primary)] mb-1">Identificación fiscal</h2>
                  <p class="text-sm text-[var(--text-secondary)] mb-6">Usamos este dato para registrar correctamente tu alta administrativa.</p>
                  @if (showErrors() && (!cd.taxIdType || !cd.taxIdValue)) {
                    <div class="bg-[var(--status-error-subtle)] border rounded-xl p-4 mb-6 flex items-start gap-3" style="border-color: rgba(220,38,38,0.2)">
                      <p class="text-sm font-bold text-[var(--status-error)]">Faltan campos obligatorios en este paso.</p>
                    </div>
                  }
                  <div class="space-y-5">
                    <div>
                      <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Tipo de identificación</label>
                      <select [(ngModel)]="cd.taxIdType" (ngModelChange)="updateData({ taxIdType: $event })"
                        class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)]">
                        <option value="">Seleccioná un tipo</option>
                        @for (t of taxIdTypes; track t.code) { <option [value]="t.code">{{ t.label }}</option> }
                      </select>
                    </div>
                    <div>
                      <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Número de identificación</label>
                      <input [(ngModel)]="cd.taxIdValue" (ngModelChange)="updateData({ taxIdValue: $event })"
                        [placeholder]="taxIdMask(cd.taxIdType)"
                        class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)]">
                    </div>
                  </div>
                }
                @case (2) {
                  <h2 class="text-xl font-bold text-[var(--text-primary)] mb-1">Datos de cobro</h2>
                  <p class="text-sm text-[var(--text-secondary)] mb-6">Seleccioná cómo querés registrar tus datos de cobro para el alta.</p>
                  <div class="space-y-3">
                    @for (pm of paymentMethods; track pm.value) {
                      <button (click)="updateData({ paymentMethod: pm.value })" type="button"
                        class="w-full flex items-center justify-between p-4 rounded-xl border-2 text-left"
                        [class]="cd.paymentMethod === pm.value ? 'border-[var(--brand-primary)] bg-[var(--brand-primary-subtle)]' : 'border-[var(--border-default)] hover:border-[var(--border-focus)] bg-[var(--bg-base)]'"
                      >
                        <div><p class="text-sm font-bold" [class]="cd.paymentMethod === pm.value ? 'text-[var(--brand-primary)]' : 'text-[var(--text-primary)]'">{{ pm.label }}</p><p class="text-xs text-[var(--text-secondary)] mt-0.5">{{ pm.desc }}</p></div>
                        <div class="w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0"
                          [class]="cd.paymentMethod === pm.value ? 'border-[var(--brand-primary)] bg-[var(--brand-primary)]' : 'border-[var(--border-default)]'">
                          @if (cd.paymentMethod === pm.value) { <svg class="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg> }
                        </div>
                      </button>
                    }
                  </div>
                  @if (cd.paymentMethod === 'CBU') {
                    <div class="mt-4">
                      <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">CBU</label>
                      <input [(ngModel)]="cd.cbu" (ngModelChange)="updateData({ cbu: $event })" placeholder="22 dígitos"
                        class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)] font-mono">
                    </div>
                  }
                  @if (cd.paymentMethod === 'CRYPTO') {
                    <div class="mt-4 space-y-3">
                      <div>
                        <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Tipo de wallet</label>
                        <input [(ngModel)]="cd.walletType" (ngModelChange)="updateData({ walletType: $event })" placeholder="Ej.: Binance, MetaMask"
                          class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)]">
                      </div>
                      <div>
                        <label class="block text-[11px] font-medium text-[var(--text-tertiary)] mb-1">Dirección de wallet</label>
                        <input [(ngModel)]="cd.walletAddress" (ngModelChange)="updateData({ walletAddress: $event })" placeholder="0x..."
                          class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--border-focus)] font-mono">
                      </div>
                    </div>
                  }
                }
                @case (3) {
                  <h2 class="text-xl font-bold text-[var(--text-primary)] mb-1">Referencias</h2>
                  <p class="text-sm text-[var(--text-secondary)] mb-6">Agregá al menos una referencia laboral o profesional.</p>
                  @for (ref of cd.references; track ref.id; let i = $index) {
                    <div class="bg-[var(--bg-subtle)] rounded-lg p-4 mb-3 border border-[var(--border-subtle)]">
                      <div class="flex items-center justify-between mb-2">
                        <span class="text-xs font-bold text-[var(--text-tertiary)]">Referencia {{ i + 1 }}</span>
                        <button (click)="removeReference(i)" class="text-xs text-[var(--status-error)] hover:underline">Eliminar</button>
                      </div>
                      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <input [(ngModel)]="ref.fullName" placeholder="Nombre completo" class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm outline-none focus:border-[var(--border-focus)]">
                        <input [(ngModel)]="ref.relationship" placeholder="Relación" class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm outline-none focus:border-[var(--border-focus)]">
                        <input [(ngModel)]="ref.company" placeholder="Empresa" class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm outline-none focus:border-[var(--border-focus)]">
                        <input [(ngModel)]="ref.email" placeholder="Email" class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm outline-none focus:border-[var(--border-focus)]">
                        <input [(ngModel)]="ref.phone" placeholder="Teléfono" class="w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-sm outline-none focus:border-[var(--border-focus)]">
                      </div>
                    </div>
                  }
                  <button (click)="addReference()" class="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold text-[var(--brand-primary)] bg-[var(--brand-primary-subtle)] hover:opacity-80">
                    + Agregar referencia
                  </button>
                }
                @case (4) {
                  <h2 class="text-xl font-bold text-[var(--text-primary)] mb-1">Archivos</h2>
                  <p class="text-sm text-[var(--text-secondary)] mb-6">Subí los documentos requeridos para tu alta (mock - no se suben realmente).</p>
                  <div class="border-2 border-dashed border-[var(--border-default)] rounded-xl p-8 text-center">
                    <p class="text-sm text-[var(--text-tertiary)]">Arrastrá archivos aquí o hacé clic para seleccionar</p>
                    <p class="text-[10px] text-[var(--text-tertiary)] mt-1">(Simulación - los archivos no se almacenan)</p>
                    <button (click)="mockFileUpload()" class="mt-4 inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)]">
                      Simular carga de archivo
                    </button>
                  </div>
                  @if (cd.files.length > 0) {
                    <div class="mt-4 space-y-2">
                      @for (f of cd.files; track f.id) {
                        <div class="flex items-center justify-between bg-[var(--bg-subtle)] rounded-lg p-3 border border-[var(--border-subtle)]">
                          <span class="text-sm text-[var(--text-primary)]">{{ f.name }}</span>
                          <span class="text-[10px] text-[var(--text-tertiary)]">{{ (f.sizeBytes / 1024).toFixed(1) }} KB</span>
                        </div>
                      }
                    </div>
                  }
                }
              }
            </div>

            <!-- Navigation -->
            <div class="flex items-center justify-between gap-3">
              @if (cd.currentStep > 1) {
                <button (click)="prevStep()" class="px-4 py-2 rounded-lg text-sm font-semibold border border-[var(--border-default)] text-[var(--text-secondary)] hover:bg-[var(--bg-subtle)]">
                  Anterior
                </button>
              } @else { <div></div> }

              @if (cd.currentStep < 4) {
                <button (click)="nextStep()" class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)]">
                  Siguiente
                </button>
              } @else {
                <button (click)="submitForm()" class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--brand-primary)] hover:bg-[var(--brand-primary-hover)]">
                  Enviar datos
                </button>
              }
            </div>
          </div>
        }
      }
    }
  `,
})
export class CandidateWizardComponent {
  readonly svc = inject(OnboardingMockService);
  readonly steps = STEPS;
  readonly taxIdTypes = TAX_ID_TYPES;
  readonly showErrors = signal(false);

  readonly paymentMethods = [
    { value: 'CBU' as const, label: 'Transferencia bancaria (CBU)', desc: 'Cuenta bancaria argentina' },
    { value: 'WIRE' as const, label: 'Wire transfer', desc: 'Cuenta bancaria internacional' },
    { value: 'CRYPTO' as const, label: 'Crypto', desc: 'Wallet de criptomonedas' },
  ];

  taxIdMask(type: string): string {
    return TAX_ID_TYPES.find(t => t.code === type)?.mask || 'Ingresá el número';
  }

  updateData(data: Partial<CandidateData>): void {
    const c = this.svc.selectedCase();
    if (c) this.svc.updateCandidateData(c.id, data);
  }

  nextStep(): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData) return;
    const cd = c.candidateData;

    // Validate step 1
    if (cd.currentStep === 1 && (!cd.taxIdType || !cd.taxIdValue)) {
      this.showErrors.set(true);
      return;
    }
    // Validate step 2
    if (cd.currentStep === 2 && !cd.paymentMethod) {
      this.svc.addToast('warning', 'Seleccioná un método de cobro');
      return;
    }

    this.showErrors.set(false);
    const completed = cd.completedSteps.includes(cd.currentStep) ? cd.completedSteps : [...cd.completedSteps, cd.currentStep];
    this.svc.updateCandidateData(c.id, { currentStep: cd.currentStep + 1, completedSteps: completed });
  }

  prevStep(): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData || c.candidateData.currentStep <= 1) return;
    this.svc.updateCandidateData(c.id, { currentStep: c.candidateData.currentStep - 1 });
    this.showErrors.set(false);
  }

  addReference(): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData) return;
    const newRef: Reference = { id: Date.now().toString(), fullName: '', relationship: '', company: '', email: '', phone: '' };
    this.svc.updateCandidateData(c.id, { references: [...c.candidateData.references, newRef] });
  }

  removeReference(index: number): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData) return;
    const refs = [...c.candidateData.references];
    refs.splice(index, 1);
    this.svc.updateCandidateData(c.id, { references: refs });
  }

  mockFileUpload(): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData) return;
    const newFile = { id: Date.now().toString(), fileType: 'w8' as const, name: `documento_${c.candidateData.files.length + 1}.pdf`, sizeBytes: Math.round(Math.random() * 500000) };
    this.svc.updateCandidateData(c.id, { files: [...c.candidateData.files, newFile] });
  }

  submitForm(): void {
    const c = this.svc.selectedCase();
    if (!c?.candidateData) return;
    const completed = c.candidateData.completedSteps.includes(4) ? c.candidateData.completedSteps : [...c.candidateData.completedSteps, 4];
    this.svc.updateCandidateData(c.id, { completedSteps: completed });
    this.svc.submitCandidateForm(c.id);
  }
}
