// apps/web-angular/src/app/shared/components/modal/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-modal',
  standalone: true,
  template: `
    @if (isOpen) {
      <div class="fixed inset-0 z-50 flex items-start justify-center pt-[5vh] px-4"
           (click)="onClose.emit()" (keydown.escape)="onClose.emit()">
        <div class="fixed inset-0 bg-[var(--bg-overlay)]" aria-hidden="true"></div>
        <div
          class="relative bg-[var(--bg-surface)] rounded-2xl border border-[var(--border-default)] shadow-xl w-full overflow-hidden animate-fade-in"
          [class.max-w-lg]="size === 'md'"
          [class.max-w-3xl]="size === 'lg'"
          [class.max-w-5xl]="size === 'xl'"
          style="max-height: 90vh"
          (click)="$event.stopPropagation()"
        >
          <div class="flex items-center justify-between px-6 py-4 border-b border-[var(--border-subtle)]">
            <h2 class="text-base font-bold text-[var(--text-primary)]">{{ title }}</h2>
            <button
              (click)="onClose.emit()"
              class="w-8 h-8 rounded-lg flex items-center justify-center text-[var(--text-tertiary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-subtle)]"
              aria-label="Cerrar"
            >
              <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
              </svg>
            </button>
          </div>
          <div class="px-6 py-5 overflow-y-auto" style="max-height: calc(90vh - 65px)">
            <ng-content />
          </div>
        </div>
      </div>
    }
  `,
})
export class ModalComponent {
  @Input() isOpen = false;
  @Input() title = '';
  @Input() size: 'md' | 'lg' | 'xl' = 'md';
  @Output() onClose = new EventEmitter<void>();
}

// src/components/ui/Modal.tsx
import React, { useEffect } from 'react';
import { X } from 'lucide-react';
import { cn } from '../../utils/cn';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  size?: 'sm' | 'md' | 'lg' | 'xl';
}

export function Modal({ isOpen, onClose, title, children, size = 'md' }: ModalProps) {
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const sizes = {
    sm: 'lg:max-w-md',
    md: 'lg:max-w-lg',
    lg: 'lg:max-w-2xl',
    xl: 'lg:max-w-4xl',
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end lg:items-center justify-center lg:p-4">
      <div
        className="absolute inset-0 bg-[var(--bg-overlay)]"
        onClick={onClose}
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        className={cn(
          'relative w-full bg-[var(--bg-surface)] border border-[var(--border-default)] animate-slide-in-up',
          'rounded-t-2xl lg:rounded-xl',
          sizes[size]
        )}
        style={{ boxShadow: 'var(--shadow-xl)' }}
      >
        {/* Handle visual en mobile */}
        <div className="flex justify-center pt-3 pb-1 lg:hidden">
          <div className="w-10 h-1 rounded-full bg-[var(--border-strong)]" />
        </div>
        <div className="flex items-center justify-between px-6 py-3 lg:py-4 border-b border-[var(--border-subtle)]">
          <h2 id="modal-title" className="text-base lg:text-lg font-semibold text-[var(--text-primary)]">{title}</h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[var(--text-tertiary)] hover:text-[var(--text-primary)] hover:bg-white/[0.05] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        <div className="px-6 py-4 max-h-[80vh] lg:max-h-[calc(100vh-200px)] overflow-y-auto">
          {children}
        </div>
      </div>
    </div>
  );
}
