// apps/web-angular/src/app/shared/components/toast/toast.component.ts
import { Component, inject } from '@angular/core';
import { OnboardingMockService } from '../../../onboarding/services/onboarding-mock.service';

@Component({
  selector: 'app-toast-container',
  standalone: true,
  template: `
    <div class="fixed bottom-4 right-4 z-[60] flex flex-col gap-2 max-w-sm">
      @for (toast of svc.toasts(); track toast.id) {
        <div
          class="flex items-start gap-3 px-4 py-3 rounded-xl border shadow-lg animate-slide-in"
          [class]="toastClass(toast.type)"
        >
          <div class="flex-1 min-w-0">
            <p class="text-sm font-bold">{{ toast.title }}</p>
            @if (toast.message) {
              <p class="text-xs mt-0.5 opacity-80">{{ toast.message }}</p>
            }
          </div>
          <button
            (click)="svc.removeToast(toast.id)"
            class="flex-shrink-0 w-5 h-5 flex items-center justify-center rounded opacity-60 hover:opacity-100"
            aria-label="Cerrar"
          >×</button>
        </div>
      }
    </div>
  `,
})
export class ToastContainerComponent {
  readonly svc = inject(OnboardingMockService);

  toastClass(type: string): string {
    switch (type) {
      case 'success': return 'bg-[var(--status-success-subtle)] border-[var(--status-success)]/20 text-[var(--status-success)]';
      case 'error':   return 'bg-[var(--status-error-subtle)] border-[var(--status-error)]/20 text-[var(--status-error)]';
      case 'warning': return 'bg-[var(--status-warning-subtle)] border-[var(--status-warning)]/20 text-[var(--status-warning)]';
      default:        return 'bg-[var(--status-info-subtle)] border-[var(--status-info)]/20 text-[var(--status-info)]';
    }
  }
}

// src/components/ui/Toast.tsx
import { CheckCircle, XCircle, AlertTriangle, Info, X } from 'lucide-react';
import { cn } from '../../utils/cn';
import { useStore, Toast as ToastType } from '../../store';

const icons = {
  success: CheckCircle,
  error: XCircle,
  warning: AlertTriangle,
  info: Info,
};

const colors = {
  success: 'var(--status-success)',
  error: 'var(--status-error)',
  warning: 'var(--status-warning)',
  info: 'var(--status-info)',
};

function ToastItem({ toast }: { toast: ToastType }) {
  const removeToast = useStore(state => state.removeToast);
  const Icon = icons[toast.type];

  return (
    <div
      role="alert"
      className={cn(
        'flex items-start gap-3 bg-[var(--bg-elevated)] border rounded-xl px-4 py-3 animate-slide-in-up transition-[border-color,background-color] duration-150',
        'min-w-[300px] max-w-[400px]'
      )}
      style={{ borderColor: colors[toast.type], boxShadow: 'var(--shadow-lg)' }}
    >
      <Icon className="w-5 h-5 flex-shrink-0 mt-0.5" style={{ color: colors[toast.type] }} />
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-[var(--text-primary)]">{toast.title}</p>
        {toast.message && (
          <p className="text-xs text-[var(--text-secondary)] mt-0.5">{toast.message}</p>
        )}
      </div>
      <button
        onClick={() => removeToast(toast.id)}
        className="p-1 rounded text-[var(--text-tertiary)] hover:text-[var(--text-primary)] hover:bg-white/[0.05] transition-colors"
      >
        <X className="w-4 h-4" />
      </button>
    </div>
  );
}

export function ToastContainer() {
  const toasts = useStore(state => state.toasts);

  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col gap-3">
      {toasts.map(toast => (
        <ToastItem key={toast.id} toast={toast} />
      ))}
    </div>
  );
}
